### ISSUE TITLE
factoryFor return value should be {create, class}

### ISSUE THREAD

**Issue by mixonic** [glimmerjs/glimmer-di#20]
[factoryFor](https://github.com/glimmerjs/glimmer-di/blob/8ea5c6b0e0cdeb65750c67ba2a059b0743723c34/src/container.ts#L19) currently returns the factory literal. [Ember's `factoryFor`](https://github.com/emberjs/ember.js/blob/0836afc771eadb8b51ce3c29bbc7cf481661b787/packages/container/lib/container.js#L675) returns an object `{create, class}`. `class` is simply the registered item. `create` is a function accepting an argument of initial properties for the instance, and returns an instance of the factory *with dependencies injected*. See the above links for implementation details.

@robbiepitts was attempting to use `factoryFor` on glimmer/di and noted the dependencies are missing. This probably means `factoryFor` on glimmer/di should be refactored to match Ember's behavior or that a new API is needed for glimmer/di.

**Comment by dgeb** [comment]
Implemented in #26

**Comment by dgeb** [comment]
Just merged #26
